# this is mysql config
[list]
    [list.default]
        table_prefix = "l_"
        driver_name = "mysql"
        data_source_name = "root:mima@tcp(127.0.0.1:3306)/go_live?charset=utf8&parseTime=true&loc=Asia%2FShanghai"
        max_open_conn = 20#设置打开数据库连接的最大数量
        max_idle_conn = 10#设置空闲连接池中连接的最大数量
        max_conn_life_time = 3600#设置了连接可复用的最大时间。